compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: 'no'
num_processes: 2
machine_rank: 0
main_process_ip: 127.0.0.1
main_process_port: 29500
deepspeed_config: false
dynamo_backend: 'NO'
gradient_accumulation_steps: 8
