[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020
    Log_File      /var/log/fluent-bit/fluent-bit.log

[INPUT]
    Name              tail
    Path              /var/log/apache2/access.log
    Path_Key          source
    Tag               web.access
    DB                /var/lib/fluent-bit/logguard-state.db
    Refresh_Interval  5
    Read_from_Head    false
    Skip_Long_Lines   On
    Skip_Empty_Lines  On
    Mem_Buf_Limit     50MB
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size   5MB

[OUTPUT]
    Name              http
    Match             web.access
    Host              localhost
    Port              8000
    URI               /api/v1/logs/agent/send-logs
    Format            json
    Retry_Limit       5
    Header            X-API-Key replace-with-project-ingest-api-key
